"""add_soft_delete_to_game_glossary

Revision ID: 5e82a3cd7885
Revises: 7aed83a596d9
Create Date: 2026-01-23 16:50:34.894917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e82a3cd7885'
down_revision = '7aed83a596d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_glossary',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('translated_term', sa.String(length=255), nullable=False),
    sa.Column('language_pair', sa.String(length=255), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_glossary_id'), 'game_glossary', ['id'], unique=False)
    op.drop_index('ix_game_glossarys_id', table_name='game_glossarys')
    op.drop_table('game_glossarys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_glossarys',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('game_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('game_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_category_id'], ['game_category.id'], name='game_glossarys_game_category_id_fkey'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='game_glossarys_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_glossarys_pkey')
    )
    op.create_index('ix_game_glossarys_id', 'game_glossarys', ['id'], unique=False)
    op.drop_index(op.f('ix_game_glossary_id'), table_name='game_glossary')
    op.drop_table('game_glossary')
    # ### end Alembic commands ###

