"""Add game module

Revision ID: a444366d585c
Revises: ed63df5172b0
Create Date: 2026-01-22 10:21:09.493157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a444366d585c'
down_revision = 'ed63df5172b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

