"""Add global_glossary module

Revision ID: b90b7723c586
Revises: 5101f4d600eb
Create Date: 2026-01-25 22:31:32.952548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90b7723c586'
down_revision = '5101f4d600eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

