"""Add asset module

Revision ID: c775177c2fc1
Revises: 153976a54c5d
Create Date: 2026-01-20 11:13:42.698015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c775177c2fc1'
down_revision = '153976a54c5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nopes_id', table_name='nopes')
    op.drop_table('nopes')
    op.alter_column('game_category', 'translation_style',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('jobs', sa.Column('job_code', sa.String(length=50), nullable=False))
    op.add_column('jobs', sa.Column('job_type', sa.String(length=50), nullable=False))
    op.add_column('jobs', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('jobs', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.add_column('jobs', sa.Column('team_id', sa.BigInteger(), nullable=True))
    op.add_column('jobs', sa.Column('game_id', sa.BigInteger(), nullable=True))
    op.add_column('jobs', sa.Column('game_genre', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('source_lang', sa.String(length=10), nullable=True))
    op.add_column('jobs', sa.Column('target_lang', sa.String(length=10), nullable=True))
    op.add_column('jobs', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('max_retry', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('jobs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'jobs', ['job_code'])
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'title')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='unique')
    op.alter_column('jobs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('jobs', 'finished_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'result')
    op.drop_column('jobs', 'payload')
    op.drop_column('jobs', 'max_retry')
    op.drop_column('jobs', 'retry_count')
    op.drop_column('jobs', 'progress')
    op.drop_column('jobs', 'target_lang')
    op.drop_column('jobs', 'source_lang')
    op.drop_column('jobs', 'game_genre')
    op.drop_column('jobs', 'game_id')
    op.drop_column('jobs', 'team_id')
    op.drop_column('jobs', 'user_id')
    op.drop_column('jobs', 'priority')
    op.drop_column('jobs', 'status')
    op.drop_column('jobs', 'job_type')
    op.drop_column('jobs', 'job_code')
    op.alter_column('game_category', 'translation_style',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.create_table('nopes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('job_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('game_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('game_genre', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_lang', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('target_lang', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_retry', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nopes_pkey'),
    sa.UniqueConstraint('job_code', name='nopes_job_code_key')
    )
    op.create_index('ix_nopes_id', 'nopes', ['id'], unique=False)
    # ### end Alembic commands ###

