/**
 * Tên ngôn ngữ tiếng Việt theo danh sách Google Dịch (translate.google.com).
 * Dùng để hiển thị thống nhất trong app.
 */

export const LANGUAGE_NAMES_VI: Record<string, string> = {
  en: 'Tiếng Anh',
  vi: 'Tiếng Việt',
  ja: 'Tiếng Nhật',
  ko: 'Tiếng Hàn',
  zh: 'Tiếng Trung',
  'zh-CN': 'Tiếng Trung (Giản thể)',
  'zh-TW': 'Tiếng Trung (Phồn thể)',
  th: 'Tiếng Thái',
  id: 'Tiếng Indonesia',
  ms: 'Tiếng Mã Lai',
  fr: 'Tiếng Pháp',
  de: 'Tiếng Đức',
  es: 'Tiếng Tây Ban Nha',
  pt: 'Tiếng Bồ Đào Nha',
  'pt-BR': 'Tiếng Bồ Đào Nha (Brazil)',
  'pt-PT': 'Tiếng Bồ Đào Nha (Bồ Đào Nha)',
  ru: 'Tiếng Nga',
  ar: 'Tiếng Ả Rập',
  hi: 'Tiếng Hindi',
  it: 'Tiếng Ý',
  nl: 'Tiếng Hà Lan',
  pl: 'Tiếng Ba Lan',
  tr: 'Tiếng Thổ Nhĩ Kỳ',
  uk: 'Tiếng Ukraina',
  cs: 'Tiếng Séc',
  el: 'Tiếng Hy Lạp',
  he: 'Tiếng Do Thái',
  hu: 'Tiếng Hungary',
  ro: 'Tiếng Romania',
  sv: 'Tiếng Thụy Điển',
  da: 'Tiếng Đan Mạch',
  fi: 'Tiếng Phần Lan',
  no: 'Tiếng Na Uy',
  bg: 'Tiếng Bulgaria',
  hr: 'Tiếng Croatia',
  sk: 'Tiếng Slovak',
  sl: 'Tiếng Slovenia',
  sr: 'Tiếng Serbia',
  ca: 'Tiếng Catalan',
  eu: 'Tiếng Basque',
  sw: 'Tiếng Swahili',
  af: 'Tiếng Afrikaans',
  sq: 'Tiếng Albania',
  am: 'Tiếng Amharic',
  hy: 'Tiếng Armenia',
  az: 'Tiếng Azerbaijan',
  bn: 'Tiếng Bengal',
  my: 'Tiếng Myanmar',
  km: 'Tiếng Khmer',
  fil: 'Tiếng Filipino',
  ka: 'Tiếng Gruzia',
  gu: 'Tiếng Gujarat',
  kn: 'Tiếng Kannada',
  ky: 'Tiếng Kyrgyz',
  lo: 'Tiếng Lào',
  lv: 'Tiếng Latvia',
  lt: 'Tiếng Litva',
  mk: 'Tiếng Macedonia',
  ml: 'Tiếng Malayalam',
  mn: 'Tiếng Mông Cổ',
  ne: 'Tiếng Nepal',
  fa: 'Tiếng Ba Tư',
  pa: 'Tiếng Punjab',
  si: 'Tiếng Sinhala',
  ta: 'Tiếng Tamil',
  te: 'Tiếng Telugu',
  ur: 'Tiếng Urdu',
  uz: 'Tiếng Uzbek',
  cy: 'Tiếng Wales',
  xh: 'Tiếng Xhosa',
  zu: 'Tiếng Zulu',
  ha: 'Tiếng Hausa',
  ig: 'Tiếng Igbo',
  yi: 'Tiếng Yiddish',
  yo: 'Tiếng Yoruba',
  ga: 'Tiếng Ireland',
  mt: 'Tiếng Malta',
  mi: 'Tiếng Maori',
  ps: 'Tiếng Pashto',
  sd: 'Tiếng Sindhi',
  sn: 'Tiếng Shona',
  so: 'Tiếng Somali',
  tg: 'Tiếng Tajik',
  tk: 'Tiếng Turkmen',
  jw: 'Tiếng Java',
  ceb: 'Tiếng Cebuano',
  co: 'Tiếng Corsica',
  eo: 'Tiếng Quốc tế ngữ',
  fy: 'Tiếng Frisian',
  gd: 'Tiếng Scots Gaelic',
  hmn: 'Tiếng Hmong',
  ht: 'Tiếng Creole Haiti',
  haw: 'Tiếng Hawaii',
  ku: 'Tiếng Kurd',
  lb: 'Tiếng Luxembourg',
  ny: 'Tiếng Chichewa',
  sm: 'Tiếng Samoa',
  st: 'Tiếng Sesotho',
  su: 'Tiếng Sunda',
  tt: 'Tiếng Tatar',
};

/**
 * Trả về tên ngôn ngữ tiếng Việt (theo Google Dịch).
 * Nếu không có trong bảng thì trả về fallback (tên từ API hoặc mã code).
 */
export function getLanguageNameVi(code: string, fallback?: string): string {
  if (!code || typeof code !== 'string') return fallback ?? '';
  const s = code.trim();
  const exact = LANGUAGE_NAMES_VI[s] ?? LANGUAGE_NAMES_VI[s.toLowerCase()];
  if (exact) return exact;
  return fallback ?? s;
}
