"""Add job module

Revision ID: 9c55c1d5b35c
Revises: a74cf86b60e9
Create Date: 2026-01-12 17:23:50.501005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c55c1d5b35c'
down_revision = 'a74cf86b60e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_entriess',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_entriess_id'), 'glossary_entriess', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_code', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('game_id', sa.BigInteger(), nullable=True),
    sa.Column('game_genre', sa.String(length=50), nullable=True),
    sa.Column('source_lang', sa.String(length=10), nullable=True),
    sa.Column('target_lang', sa.String(length=10), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retry', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_code')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.drop_index('ix_language_pairs_organization', table_name='language_pairs')
    op.drop_index('ix_language_pairs_source_target', table_name='language_pairs')
    op.alter_column('languages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('settings', 'key',
               existing_type=sa.VARCHAR(length=255),
               comment='Key của setting (unique)',
               existing_nullable=False)
    op.alter_column('settings', 'category',
               existing_type=sa.VARCHAR(length=12),
               comment='Danh mục setting',
               existing_nullable=False)
    op.alter_column('settings', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Tên hiển thị',
               existing_nullable=False)
    op.alter_column('settings', 'description',
               existing_type=sa.TEXT(),
               comment='Mô tả',
               existing_nullable=True)
    op.alter_column('settings', 'value',
               existing_type=sa.TEXT(),
               comment='Giá trị (lưu dạng text, parse theo type)',
               existing_nullable=True)
    op.alter_column('settings', 'type',
               existing_type=sa.VARCHAR(length=7),
               comment='Loại dữ liệu',
               existing_nullable=False)
    op.alter_column('settings', 'is_encrypted',
               existing_type=sa.BOOLEAN(),
               comment='Có mã hóa không (cho password, API keys)',
               existing_nullable=False)
    op.alter_column('settings', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment='Có public không (frontend có thể đọc)',
               existing_nullable=False)
    op.alter_column('settings', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Trạng thái active',
               existing_nullable=False)
    op.alter_column('settings', 'order',
               existing_type=sa.INTEGER(),
               comment='Thứ tự hiển thị',
               existing_nullable=False)
    op.alter_column('settings', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Metadata bổ sung (validation rules, options, etc.)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Metadata bổ sung (validation rules, options, etc.)',
               existing_nullable=True)
    op.alter_column('settings', 'order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Thứ tự hiển thị',
               existing_nullable=False)
    op.alter_column('settings', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Trạng thái active',
               existing_nullable=False)
    op.alter_column('settings', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Có public không (frontend có thể đọc)',
               existing_nullable=False)
    op.alter_column('settings', 'is_encrypted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Có mã hóa không (cho password, API keys)',
               existing_nullable=False)
    op.alter_column('settings', 'type',
               existing_type=sa.VARCHAR(length=7),
               comment=None,
               existing_comment='Loại dữ liệu',
               existing_nullable=False)
    op.alter_column('settings', 'value',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Giá trị (lưu dạng text, parse theo type)',
               existing_nullable=True)
    op.alter_column('settings', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Mô tả',
               existing_nullable=True)
    op.alter_column('settings', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Tên hiển thị',
               existing_nullable=False)
    op.alter_column('settings', 'category',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Danh mục setting',
               existing_nullable=False)
    op.alter_column('settings', 'key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Key của setting (unique)',
               existing_nullable=False)
    op.alter_column('languages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('ix_language_pairs_source_target', 'language_pairs', ['source_language_id', 'target_language_id'], unique=False)
    op.create_index('ix_language_pairs_organization', 'language_pairs', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_glossary_entriess_id'), table_name='glossary_entriess')
    op.drop_table('glossary_entriess')
    # ### end Alembic commands ###

