"""Add global_glossary module

Revision ID: 3eef5839b10d
Revises: 695422708ac5
Create Date: 2026-01-23 11:25:09.081244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3eef5839b10d'
down_revision = '695422708ac5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_glossarys',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('term', sa.String(length=255), nullable=False),
        sa.Column('translated_term', sa.String(length=255), nullable=False),
        sa.Column('game_category_id', sa.Integer(), nullable=False),
        sa.Column('language_pair', sa.String(length=10), nullable=False),
        sa.Column('usage_count', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['game_category_id'], ['game_category.id'], name='global_glossarys_game_category_id_fkey'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_glossarys_id'), 'global_glossarys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_glossarys_id'), table_name='global_glossarys')
    op.drop_table('global_glossarys')
    # ### end Alembic commands ###

