"""Add global_glossary module

Revision ID: 4fda4ac5b5b5
Revises: 3eef5839b10d
Create Date: 2026-01-23 11:54:31.575345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fda4ac5b5b5'
down_revision = '3eef5839b10d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

