"""Add game_glossagy module

Revision ID: 5101f4d600eb
Revises: f78d89cdd243
Create Date: 2026-01-25 12:34:23.714997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5101f4d600eb'
down_revision = 'f78d89cdd243'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_glossaries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('translation_term', sa.String(length=255), nullable=False),
    sa.Column('language_pair', sa.String(length=255), nullable=False),
    sa.Column('usage_count', sa.String(length=255), nullable=True),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_glossaries_id'), 'game_glossaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_glossaries_id'), table_name='game_glossaries')
    op.drop_table('game_glossaries')
    # ### end Alembic commands ###

