"""Add global_glossary module

Revision ID: 5c7227070bf7
Revises: b90b7723c586
Create Date: 2026-01-25 22:35:26.638852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7227070bf7'
down_revision = 'b90b7723c586'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_glossary',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('translated_term', sa.String(length=255), nullable=False),
    sa.Column('language_pair', sa.String(length=255), nullable=False),
    sa.Column('game_category_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_category_id'], ['game_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_glossary_id'), 'global_glossary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_glossary_id'), table_name='global_glossary')
    op.drop_table('global_glossary')
    # ### end Alembic commands ###

