"""Add global_glosary module

Revision ID: d768f2deb28b
Revises: 5cfe28805b48
Create Date: 2026-01-26 17:45:53.539429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd768f2deb28b'
down_revision = '5cfe28805b48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_entriess',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_entriess_id'), 'glossary_entriess', ['id'], unique=False)
    op.create_table('game_glossary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['game_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_glossary_id'), 'game_glossary', ['id'], unique=False)
    op.drop_index('ix_global_glossary_id', table_name='global_glossary')
    op.drop_table('global_glossary')
    op.drop_index('ix_game_glossaries_id', table_name='game_glossaries')
    op.drop_table('game_glossaries')
    op.drop_index('ix_games_name', table_name='games')
    op.drop_table('games')
    op.drop_column('game_category', 'is_deleted')
    op.drop_column('game_category', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_category', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('game_category', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('games',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('games_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('game_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_category_id'], ['game_category.id'], name='games_game_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='games_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_games_name', 'games', ['name'], unique=False)
    op.create_table('game_glossaries',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('term', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('translation_term', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('language_pair', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('game_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='game_glossaries_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_glossaries_pkey')
    )
    op.create_index('ix_game_glossaries_id', 'game_glossaries', ['id'], unique=False)
    op.create_table('global_glossary',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('term', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('translated_term', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('language_pair', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('game_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_category_id'], ['game_category.id'], name='global_glossary_game_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='global_glossary_pkey')
    )
    op.create_index('ix_global_glossary_id', 'global_glossary', ['id'], unique=False)
    op.drop_index(op.f('ix_game_glossary_id'), table_name='game_glossary')
    op.drop_table('game_glossary')
    op.drop_index(op.f('ix_glossary_entriess_id'), table_name='glossary_entriess')
    op.drop_table('glossary_entriess')
    # ### end Alembic commands ###

