"""Add game module

Revision ID: ed63df5172b0
Revises: e1be9d70b338
Create Date: 2026-01-22 10:15:52.485266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed63df5172b0'
down_revision = 'e1be9d70b338'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create games table first since it doesn't exist
    op.create_table('games',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('game_category_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['game_category_id'], ['game_category.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_games_name', 'games', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop games table
    op.drop_index('ix_games_name', table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###

