"""Add game_glossary module

Revision ID: fb465f22012c
Revises: 4fda4ac5b5b5
Create Date: 2026-01-23 15:46:01.868919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb465f22012c'
down_revision = '4fda4ac5b5b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_glossarys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('translation_term', sa.String(length=255), nullable=False),
    sa.Column('language_pair', sa.String(length=10), nullable=False),
    sa.Column('game_category_id', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_category_id'], ['game_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_glossarys_id'), 'game_glossarys', ['id'], unique=False)
    op.drop_index('ix_game_glossary_id', table_name='game_glossary')
    op.drop_table('game_glossary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_glossary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('term', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('translated_term', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('language_pair', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='game_glossary_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_glossary_pkey')
    )
    op.create_index('ix_game_glossary_id', 'game_glossary', ['id'], unique=False)
    op.drop_index(op.f('ix_game_glossarys_id'), table_name='game_glossarys')
    op.drop_table('game_glossarys')
    # ### end Alembic commands ###

