"""Add global_glossary module

Revision ID: fda90613a86f
Revises: fb465f22012c
Create Date: 2026-01-23 15:53:37.239235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda90613a86f'
down_revision = 'fb465f22012c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip table creation since global_glossarys table already exists
    # op.create_table('global_glossarys', ...)
    # op.create_index(op.f('ix_global_glossarys_id'), 'global_glossarys', ['id'], unique=False)
    op.add_column('game_glossarys', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('game_glossarys', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('game_glossarys', 'translation_term')
    op.drop_column('game_glossarys', 'usage_count')
    op.drop_column('game_glossarys', 'language_pair')
    op.drop_column('game_glossarys', 'term')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_glossarys', sa.Column('term', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('game_glossarys', sa.Column('language_pair', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('game_glossarys', sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game_glossarys', sa.Column('translation_term', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('game_glossarys', 'description')
    op.drop_column('game_glossarys', 'name')
    # Skip table operations since global_glossarys table should remain
    # op.drop_index(op.f('ix_global_glossarys_id'), table_name='global_glossarys')
    # op.drop_table('global_glossarys')
    # ### end Alembic commands ###

